GET localhost:8080/accounts

###

GET localhost:8080/account/1

###

POST localhost:8080/accounts
Content-Type: application/json

{
      "id": 1,
      "name": "ddd",
      "number" : "dsfdsf",
      "balance": 100
   }


###

DELETE localhost:8080/account/2

