GET localhost:8080/system/version

###

GET localhost:8080/actuator/counter

###

POST localhost:8080/actuator/counter
Content-Type: application/json

{
  "delta": 100
}

###

DELETE  localhost:8080/actuator/counter

###

GET localhost:8080/actuator/prometheus


