= Spring Dependency Injection

=== 정의
- 프로그램에서 구성 요소간의 의존관계가 소스코드 내부가 아닌 외부의 설정파일을 통해 정의되게 하는 디자인 패턴.
- DI == design pattern, 의존성 이슈를 행동으로 분리 시키는 것.
- DI는 IoC의 구현.
- Factory method pattern 구현해보고 조건을 보며 왜 생각(factory pattern은 단지 이해하기 위한 pattern) +
=> 이해안된다면 다이어그램 그려보고 csvApplication이 없이 Appliatcation에서 직접적으로 사용할때의 문제점 생각. +
=> Spring DI는 어디에 무엇을 Injection하는지, .
* Problem +
1. 사용자에게 다양한 문서를 읽어서 객체로 결과를 반환하는 프레임워크 개발을 해야 합니다.
2. Application 클래스와 Document 클래스로 추상화 할수 있는데, 이 두 클래스는 모두 추상 클래스이고 이 클래스들을 상속해서 문서의 종류에 따른 대응을 할 수 있습니다.
3. Application 클래스는 언제 Document 클래스를 생성하고 사용해야 하는지는 알 수 있지만 프레임워크에서 구체적으로 어떤 문서를 처리할 Document 를 생성해야 하는지는 결정 할 수 없습니다.
* Solution +
1. Document 의 서브클래스 중 어느 클래스를 생성하는 지는 Application 클래스의 서브클래스가 결정하도록 설계합니다.
2. Application 클래스의 서브클래스는 추상화된 createDocument()메소드를 정의하여 적당한 Document 클래스의 서브클래스를 반환하도록 합니다.
3. createDocument() 메소드를 factory method 라고 부릅니다.
* Consequences +
 => 구체적인 클래스(CsvDocument)가 추상클래스(Application)에 종속되지 않도록 구현할 수 있습니다.

=== 방법
1. Constructor Injection
1. Setter Injection
1. Field Injection

---
== 1. Constructor Injection
- Document Class constructor에 Injection할 Spring Bean을 Parameter로 생성
- 밑에 예제를 생각하면 Document를 parameter로한 constuctor가 필요하다.
- why? +
=> 의존관계를 설정파일로 정의해야 되기 때문에.

*java code*
----
class Application {
    private final Document document;

    Application(Document document){
        this.document = document;
    }

    void openDocument(){
        ...
    };
}
----

*xml code*
----
<bean id="csvDocument" class="${classPath}" />

<bean id="application" class="${classPath}"  >
    // constructor-arg 를 통해 application에 cvsDocument Bean을 Injection
    <constructor-arg ref="csvDocument" />
</bean>
----

== 2. Setter Injection
- Service Class에서는 기본 생성자를 필요로하고 setter method가 필요하다.
-

*java code*
----
class Application {
    private Document document;

//     Application(){
//     }

    void setDocument(Document document){
        this.document = document;
    }

    void openDocument(){
        ...
    };
}
----

*xml code*
----
<bean id="csvDocument" class="${classPath}" />

<bean id="application" class="${classPath}"  >
    // setDocument method에서 set은 제거하고 D는 소문자로 변환하여 읽어온다.
    <property name="document" ref="csvDocument">
</bean>
----