GET localhost:8080/accounts

###

GET localhost:8080/account/1

###

POST localhost:8080/account
Content-Type: application/json

{
      "id": 2,
      "name": "ddd",
      "score": 100
   }


###

DELETE localhost:8080/account/2

