POST localhost:8080/users
Content-Type: application/json

{
  "id" : "user",
  "password": "123"
}

###

GET localhost:8080/users/user

###

PUT localhost:8080/users/user
Content-Type: application/json

{
  "password" : "1234"
}

###


DELETE localhost:8080/users/user