POST  http://localhost:8080/residents
Content-type: application/json

{
  "residentSerialNumber": 123,
  "name": "father",
  "residentRegistrationNumber" : "123456-1234567",
  "genderCode": "male",
  "birthDate": "1999-11-27T00:00:00Z",
  "deathDate": null,
  "birthPlaceCode": "pc room",
  "registrationBaseAddress": "boseong",
  "deathPlaceCode": null,
  "deathPlaceAddress": null
}

###

PUT http://localhost:8080/residents/13
Content-Type: application/json

{
  "deathDate": "1999-11-27T00:00:00Z",
  "deathPlaceCode": "pc room",
  "deathPlaceAddress": "boseong"
}

